spring:
  security:
    oauth2:
      client: # OAuth2 클라이언트 설정
        registration: # 로그인 서비스 등록 영역 (google, kakao, naver)
          google:
            client-id: "27326569433-37asc7ec60uq68sujfe3ooaud6i9puo7.apps.googleusercontent.com"
            client-secret: "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"
            redirect-uri: "{baseUrl}/login/oauth2/code/{registrationId}" # 구글 로그인 성공 후 돌아올 url (http://localhost:8080/login/oauth2/code/google)
            scope: # 요청할 권한 목록 (email, profile)
              - email
              - profile
        provider: # OAuth2 인증 제공자 정보 명시 (옵션)
          google:
            authorization-uri: https://accounts.google.com/o/oauth2/v2/auth
            token-uri: https://oauth2.googleapis.com/token
            user-info-uri: https://www.googleapis.com/oauth2/v3/userinfo
